[package]
name = "infor"
version = "0.1.0"
edition = "2021"
authors = ["Chris Parker <mrcsparker@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.0" }
rayon = "1.7.0"
sysinfo = "0.29.8"
